package com.adielcalixto.ifacademico.presentation

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF4A6741)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFCFE8C3)
val onPrimaryContainerLight = Color(0xFF10200C)

val secondaryLight = Color(0xFF546077)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD8E2F0)
val onSecondaryContainerLight = Color(0xFF101B2C)

val tertiaryLight = Color(0xFF7B4A3A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDBCF)
val onTertiaryContainerLight = Color(0xFF2C1509)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)

val backgroundLight = Color(0xFFF8F8F8)
val onBackgroundLight = Color(0xFF1A1C1E)
val surfaceLight = Color(0xFFFFFBFF)
val onSurfaceLight = Color(0xFF1A1C1E)
val surfaceVariantLight = Color(0xFFDFE2E6)
val onSurfaceVariantLight = Color(0xFF43474E)
val outlineLight = Color(0xFF73777F)
val outlineVariantLight = Color(0xFFC3C6CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3033)
val inverseOnSurfaceLight = Color(0xFFF1F0F4)
val inversePrimaryLight = Color(0xFFA5CE9A)
val surfaceDimLight = Color(0xFFDBDADD)
val surfaceBrightLight = Color(0xFFFFFBFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F5F5)
val surfaceContainerLight = Color(0xFFEFEFEF)
val surfaceContainerHighLight = Color(0xFFE9E9E9)
val surfaceContainerHighestLight = Color(0xFFE3E3E3)

// Dark theme
val primaryDark = Color(0xFF4E7B4C)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF2A4D2B)
val onPrimaryContainerDark = Color(0xFFC8E6C9)

val secondaryDark = Color(0xFF4A5E4B)
val onSecondaryDark = Color(0xFFFFFFFF)
val secondaryContainerDark = Color(0xFF2E3D2F)
val onSecondaryContainerDark = Color(0xFFC4D3C5)

val tertiaryDark = Color(0xFFE07A5F)
val onTertiaryDark = Color(0xFFFFFFFF)
val tertiaryContainerDark = Color(0xFF7A3825)
val onTertiaryContainerDark = Color(0xFFFFD5C8)

val errorDark = Color(0xFFCF6679)
val onErrorDark = Color(0xFFFFFFFF)
val errorContainerDark = Color(0xFF5C1E2A)
val onErrorContainerDark = Color(0xFFFFD8DD)

val backgroundDark = Color(0xFF121212)
val onBackgroundDark = Color(0xFFE0E0E0)
val surfaceDark = Color(0xFF1E1E1E)
val onSurfaceDark = Color(0xFFE3E3E3)
val surfaceVariantDark = Color(0xFF2A2A2A)
val onSurfaceVariantDark = Color(0xFFA0A0A0)
val outlineDark = Color(0xFF3A3A3A)
val outlineVariantDark = Color(0xFF3D4A3E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E0E0)
val inverseOnSurfaceDark = Color(0xFF212121)
val inversePrimaryDark = Color(0xFF80C38D)
val surfaceDimDark = Color(0xFF121212)
val surfaceBrightDark = Color(0xFF252525)
val surfaceContainerLowestDark = Color(0xFF0F0F0F)
val surfaceContainerLowDark = Color(0xFF141414)
val surfaceContainerDark = Color(0xFF1C1C1C)
val surfaceContainerHighDark = Color(0xFF242424)
val surfaceContainerHighestDark = Color(0xFF2E2E2E)

// Purple theme - Dracula-inspired
val primaryPurple = Color(0xFF8B7EC8)
val onPrimaryPurple = Color(0xFFFFFFFF)
val primaryContainerPurple = Color(0xFF5B5499)
val onPrimaryContainerPurple = Color(0xFFEAE0FF)

val secondaryPurple = Color(0xFF7B8FBF)
val onSecondaryPurple = Color(0xFFFFFFFF)
val secondaryContainerPurple = Color(0xFF2E3354)
val onSecondaryContainerPurple = Color(0xFFD0D8F5)

val tertiaryPurple = Color(0xFFFFB86C)
val onTertiaryPurple = Color(0xFF282A36)
val tertiaryContainerPurple = Color(0xFFCC7A1A)
val onTertiaryContainerPurple = Color(0xFFFFDDB3)

val errorPurple = Color(0xFFCF6679)
val onErrorPurple = Color(0xFFFFFFFF)
val errorContainerPurple = Color(0xFF5C1E2A)
val onErrorContainerPurple = Color(0xFFFFD8DD)

val backgroundPurple = Color(0xFF1E1F29)
val onBackgroundPurple = Color(0xFFF8F8F2)
val surfacePurple = Color(0xFF282A36)
val onSurfacePurple = Color(0xFFF8F8F2)
val surfaceVariantPurple = Color(0xFF44475A)
val onSurfaceVariantPurple = Color(0xFFCDCED6)
val outlinePurple = Color(0xFF4A5578)
val outlineVariantPurple = Color(0xFF5C5875)
val scrimPurple = Color(0xFF000000)
val inverseSurfacePurple = Color(0xFFF8F8F2)
val inverseOnSurfacePurple = Color(0xFF282A36)
val inversePrimaryPurple = Color(0xFF7B4ACC)
val surfaceDimPurple = Color(0xFF12131A)
val surfaceBrightPurple = Color(0xFF323442)
val surfaceContainerLowestPurple = Color(0xFF0E0F15)
val surfaceContainerLowPurple = Color(0xFF17181F)
val surfaceContainerPurple = Color(0xFF1E1F29)
val surfaceContainerHighPurple = Color(0xFF252631)
val surfaceContainerHighestPurple = Color(0xFF2D2E3A)

// Yellow theme - pastel light
val primaryYellow = Color(0xFFC9960A)
val onPrimaryYellow = Color(0xFFFFFFFF)
val primaryContainerYellow = Color(0xFFFFF0C4)
val onPrimaryContainerYellow = Color(0xFF251E00)

val secondaryYellow = Color(0xFF8C7040)
val onSecondaryYellow = Color(0xFFFFFFFF)
val secondaryContainerYellow = Color(0xFFF5E6C8)
val onSecondaryContainerYellow = Color(0xFF2E2200)

val tertiaryYellow = Color(0xFF9C6FA0)
val onTertiaryYellow = Color(0xFFFFFFFF)
val tertiaryContainerYellow = Color(0xFFF3E0F5)
val onTertiaryContainerYellow = Color(0xFF2E1230)

val errorYellow = Color(0xFFBA1A1A)
val onErrorYellow = Color(0xFFFFFFFF)
val errorContainerYellow = Color(0xFFFFDAD6)
val onErrorContainerYellow = Color(0xFF410002)

val backgroundYellow = Color(0xFFFFF8E1)
val onBackgroundYellow = Color(0xFF1D1B16)
val surfaceYellow = Color(0xFFFFF8E1)
val onSurfaceYellow = Color(0xFF1D1B16)
val surfaceVariantYellow = Color(0xFFE9DCC9)
val onSurfaceVariantYellow = Color(0xFF4F4539)
val outlineYellow = Color(0xFF817567)
val outlineVariantYellow = Color(0xFFD4C4B0)
val scrimYellow = Color(0xFF000000)
val inverseSurfaceYellow = Color(0xFF33302C)
val inverseOnSurfaceYellow = Color(0xFFF7F0E7)
val inversePrimaryYellow = Color(0xFFF0C05A)
val surfaceDimYellow = Color(0xFFE4D9C4)
val surfaceBrightYellow = Color(0xFFFFFDF5)
val surfaceContainerLowestYellow = Color(0xFFFFFFFF)
val surfaceContainerLowYellow = Color(0xFFFFF9E6)
val surfaceContainerYellow = Color(0xFFFFF5D9)
val surfaceContainerHighYellow = Color(0xFFF8EFD9)
val surfaceContainerHighestYellow = Color(0xFFF5E8CC)

// Blue theme - pastel light
val primaryBlue = Color(0xFF5BA3E0)
val onPrimaryBlue = Color(0xFFFFFFFF)
val primaryContainerBlue = Color(0xFFD6E9FF)
val onPrimaryContainerBlue = Color(0xFF001D33)

val secondaryBlue = Color(0xFFE06B98)
val onSecondaryBlue = Color(0xFFFFFFFF)
val secondaryContainerBlue = Color(0xFFFFD9E8)
val onSecondaryContainerBlue = Color(0xFF3D0014)

val tertiaryBlue = Color(0xFFAB8FD6)
val onTertiaryBlue = Color(0xFFFFFFFF)
val tertiaryContainerBlue = Color(0xFFE8DDFF)
val onTertiaryContainerBlue = Color(0xFF2D0052)

val errorBlue = Color(0xFFBA1A1A)
val onErrorBlue = Color(0xFFFFFFFF)
val errorContainerBlue = Color(0xFFFFDAD6)
val onErrorContainerBlue = Color(0xFF410002)

val backgroundBlue = Color(0xFFF8FAFF)
val onBackgroundBlue = Color(0xFF1A1C1E)
val surfaceBlue = Color(0xFFF8FAFF)
val onSurfaceBlue = Color(0xFF1A1C1E)
val surfaceVariantBlue = Color(0xFFDFE2EB)
val onSurfaceVariantBlue = Color(0xFF43474E)
val outlineBlue = Color(0xFF73777F)
val outlineVariantBlue = Color(0xFFC3C6CF)
val scrimBlue = Color(0xFF000000)
val inverseSurfaceBlue = Color(0xFF2F3033)
val inverseOnSurfaceBlue = Color(0xFFF1F0F4)
val inversePrimaryBlue = Color(0xFFA0C9FF)
val surfaceDimBlue = Color(0xFFDFE2EB)
val surfaceBrightBlue = Color(0xFFF8FAFF)
val surfaceContainerLowestBlue = Color(0xFFFFFFFF)
val surfaceContainerLowBlue = Color(0xFFF5F5FF)
val surfaceContainerBlue = Color(0xFFEEF1F8)
val surfaceContainerHighBlue = Color(0xFFE8ECEF)
val surfaceContainerHighestBlue = Color(0xFFE2E5EA)
